#!/usr/bin/env python3
"""系列廣告 Short《你早就在用機器學習》配音合成（垂直 1080x1920）。

沿用 build_voice.py 的 MiniMax 克隆聲與內容雜湊，只產出 shortIntro 專用 manifest
+ 音檔 + srt。在系列資料夾根目錄執行：
    python3 tools/build_short_intro_voice.py
"""
import json
import sys
from pathlib import Path

ROOT = Path.cwd()
sys.path.insert(0, str(ROOT / "tools"))
# build_voice.py 的 argparse 在 import 時就跑，先餵一組合法 argv（用 EP5 的 model＝speech-2.8-hd）
sys.argv = ["build_voice.py", "--ep", "5"]
import build_voice as bv  # noqa: E402  (minimax / probe / cue_hash / caption_text / audio_text)

FPS = 30
GAP_S = 0.14
AUDIO_DIR = ROOT / "remotion" / "public" / "audio" / "shortIntro"
TS_OUT = ROOT / "remotion" / "src" / "shortIntroData.ts"
SRT_OUT = ROOT / "episodes" / "shortIntro.srt"

# 只在 Short 多套的替換（series.yaml 的 tts_replacements 仍由 bv.audio_text 先套）
SHORT_TTS = {
    "ML": "M L",
}

# 旁白（廣告語言：痛點＋慾望，不用術語當鉤子）
NARRATION = [
    "在 AI 充斥的時代，是不是常常聽不懂大家在聊什麼術語？",
    "想寫點跟傳統統計不一樣的研究，卻不知道怎麼開始？",
    "ML 白話課就是為這個做的。不教你寫程式，把機器學習講成人話——看得懂，你就叫得動 AI 幫你做事。",
    "十七集，從零帶你到能上手：先學會問對問題、看懂結果可不可信，再帶你摸神經網路、看醫學影像、讀病歷文字，一路到生成式 AI、把模型真正上線。",
    "連結在資訊欄，從第一集開始看。下次再聊 AI，你就不用只在旁邊點頭了。",
]


def short_audio_text(sent: str) -> str:
    text = bv.audio_text(sent)
    for k, v in SHORT_TTS.items():
        text = text.replace(k, v)
    return text


def srt_ts(t):
    h = int(t // 3600); m = int(t % 3600 // 60); s = t % 60
    return f"{h:02d}:{m:02d}:{s:06.3f}".replace(".", ",")


def main():
    AUDIO_DIR.mkdir(parents=True, exist_ok=True)
    cues, srt, t = [], [], 0.0
    for i, sent in enumerate(NARRATION):
        at = short_audio_text(sent)
        h = bv.cue_hash(at)
        mp3 = AUDIO_DIR / f"{h}.mp3"
        if not mp3.exists():
            mp3.write_bytes(bv.minimax(at))
            print(f"  ♪ {i:02d} {sent[:20]}…")
        dur = bv.probe(mp3)
        cap = bv.caption_text(sent)
        cues.append({"i": i, "text": cap, "src": f"audio/shortIntro/{h}.mp3",
                     "startF": round(t * FPS), "durF": round(dur * FPS)})
        srt.append(f"{len(srt)+1}\n{srt_ts(t)} --> {srt_ts(t+dur)}\n{cap}\n")
        t += dur + GAP_S
    data = {"fps": FPS, "model": bv.MODEL, "voice": bv.CLONE, "total": round(t * FPS), "cues": cues}
    TS_OUT.write_text(
        "// AUTO-GENERATED by tools/build_short_intro_voice.py\n"
        "export const SHORT_INTRO = " + json.dumps(data, ensure_ascii=False, indent=2) + " as const;\n"
    )
    SRT_OUT.write_text("\n".join(srt))
    print(f"\n✅ {len(cues)} 段  {t:.1f}s  → shortIntroData.ts")
    for c in cues:
        print(f"   cue{c['i']} @{c['startF']/FPS:.2f}s ({c['durF']/FPS:.2f}s)")


if __name__ == "__main__":
    main()
